### ISSUE TITLE
Can symk generate top-k partially ordering plans?

### ISSUE THREAD

**Issue by hejia-zhang** [speckdavid/symk#4]
Dear authors,

I'm very interested in your planner and would like to know if this planner can generate top-k partially ordering plans?

**Comment by speckdavid** [comment]
Dear @hejia-zhang ,

thank you for your interest. SymK is currently producing only total-order plans, and we haven't considered partial-order plans yet. 

As far as I know, there is some work on converting total-order plans to partial-order plans (e.g., [Backström 1998](https://www.jair.org/index.php/jair/article/view/10210)). I suspect that such a conversion would be possible by either treating symk as a black box and post-processing the generated plan files, or using the "plan selection interface" directly.

I hope this helps. If you have any further questions, please feel free to write either here or by mail (speckd@informatik.uni-freiburg.de).

Best
David
